In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [4]:
output = pd.read_csv("./credit44_sc.csv")

In [5]:
batch_size = 32
dataset = tf.data.Dataset.from_tensor_slices(output.values)

In [6]:
dataset = dataset.shuffle(10000)

dataset = dataset.repeat().batch(batch_size)


In [8]:
iterator = dataset.make_initializable_iterator()
sess = tf.Session()
sess.run(iterator.initializer)
next_element = iterator.get_next()

In [9]:
next_element

<tf.Tensor 'IteratorGetNext:0' shape=(?, 45) dtype=int64>

In [30]:
EPOCHS = 1000
BATCH_SIZE = 16
# using two numpy arrays

dataset = tf.data.Dataset.from_tensor_slices(output.values).shuffle(100000).batch(BATCH_SIZE)
iter = dataset.make_one_shot_iterator()
x = iter.get_next()
# # make a simple model
# net = tf.layers.dense(x, 8, activation=tf.tanh) # pass the first value from iter.get_next() as input
# net = tf.layers.dense(net, 8, activation=tf.tanh)
# prediction = tf.layers.dense(net, 1, activation=tf.tanh)
# loss = tf.losses.mean_squared_error(prediction, y) # pass the second value from iter.get_net() as label
# train_op = tf.train.AdamOptimizer().minimize(loss)

y = tf.slice(x , [0,0],[BATCH_SIZE , 6] )
z = tf.slice(x , [0,7],[BATCH_SIZE , 6] )
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(EPOCHS):
        #print(np.shape(sess.run(x)))
        print(np.shape(sess.run(y)))
        print(sess.run(y))
        print(sess.run(z))
        #_, loss_value = sess.run([train_op, loss])
        #print("Iter: {}, Loss: {:.4f}".format(i, loss_value))

(16, 6)
[[ 461  450  470    0    0 7777]
 [ 491  774  563    0    0 7777]
 [ 468  562  555    0    0 7777]
 [ 478  589  589    0    0 7777]
 [ 401  569  588    1    1    0]
 [ 572  715  594    0    0 7777]
 [ 486  567  617    2    2    0]
 [ 553  506  425    4    2    2]
 [ 497  480  421    0    0 7777]
 [ 417  492  491    0    0 7777]
 [ 498  494  578    0    0 7777]
 [ 478  780  704    0    0 7777]
 [ 494  450  460    2    2    2]
 [ 469  447  431    0    0 7777]
 [ 458  512  514    1    1    2]
 [ 518  609  570    0    0 7777]]
[[   2    0    1    5   53    7]
 [   0    0    1    1   26    4]
 [   3  575    5    6   54    1]
 [   2    0    1    1   37   19]
 [   0    0    1    2   47   12]
 [   0    0    0    0   27   10]
 [   2  349    0    0   45    1]
 [   2  116    2    2   38    4]
 [   2  676    2    2   32    5]
 [   1    0    1    1   45    8]
 [   0    0    0    0   62    1]
 [   6 3935    2    2   35    1]
 [   1    0    1    3   32    9]
 [   0    0    0    0   30   10]
 

[[   1    0    0    0   55    7]
 [   1    0    0    0   34    7]
 [   1    0    1    2   36   12]
 [   3  999    5    7   33   10]
 [   2  112    4   11   30    9]
 [   1    0    0    0   42    8]
 [   1    0    0    0   36    3]
 [   1    0    2    3   33    9]
 [   2    0    4    6   37    9]
 [   5  169    5    5   44    4]
 [   0    0    1    1   45    6]
 [   5  478    0    0   44   14]
 [   1    0    1    1   32   11]
 [   0    0    3    7   42    5]
 [   2  145    4    7   58    7]
 [   4 5051    2    3   36   12]]
(16, 6)
[[ 402  450  525    0    0 7777]
 [ 533  557  544    0    0 7777]
 [ 412  450  513    0    0 7777]
 [ 401  501  425    0    0 7777]
 [ 442  568  578    0    0 7777]
 [ 464  712  651    0    0 7777]
 [ 511  555  611    0    0 7777]
 [ 500  486  431    1    1    0]
 [ 464  501  460    0    0 7777]
 [ 474  582  495    0    0 7777]
 [ 414  603  520    0    0 7777]
 [ 456  407  425    0    0 7777]
 [ 496  788  582    0    0 7777]
 [ 514  593  547    0    0 7777]
 

(16, 6)
[[ 497  809  668    0    0 7777]
 [ 480  534  410    0    0 7777]
 [ 426  510  491    0    0 7777]
 [ 445  450  460    0    0 7777]
 [ 528  577  563    2    1    7]
 [ 438  613  485    0    0 7777]
 [ 485  526  466    0    0 7777]
 [ 539  493  592    0    0 7777]
 [ 456  475  470    0    0 7777]
 [ 538  549  489    3    3    0]
 [ 462  548  619    0    0 7777]
 [ 474  603  516    0    0 7777]
 [ 422  453  495    1    1    3]
 [ 450  451  491    6    1    0]
 [ 487  617  456    0    0 7777]
 [ 550  701  656    4    2    0]]
[[   3 1485    0    0   40   11]
 [   0    0    6    6   42   11]
 [   1 1167    1    1   52   13]
 [   7  535    2    2   36    4]
 [   2    0    1    1   56    8]
 [   1    0    5   19   46    2]
 [   2  121    3    5   34    7]
 [   0    0    0    0   44    7]
 [   0    0    4   13   30    4]
 [   0    0    2    7   35    5]
 [   1    0    1    1   57    6]
 [   0    0    1    1   55    3]
 [   8 5469    0    0   44    2]
 [   0    0    0    0   54    6]
 

InvalidArgumentError: Expected size[0] in [0, 10], but got 16
	 [[node Slice_6 (defined at <ipython-input-30-91da30575efd>:15)  = Slice[Index=DT_INT32, T=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorGetNext_18, Slice_6/begin, Slice_6/size)]]

Caused by op 'Slice_6', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.5/dist-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-91da30575efd>", line 15, in <module>
    y = tf.slice(x , [0,0],[BATCH_SIZE , 6] )
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 578, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 7466, in _slice
    "Slice", input=input, begin=begin, size=size, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Expected size[0] in [0, 10], but got 16
	 [[node Slice_6 (defined at <ipython-input-30-91da30575efd>:15)  = Slice[Index=DT_INT32, T=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorGetNext_18, Slice_6/begin, Slice_6/size)]]


In [5]:
import os
import tensorflow as tf
import pandas as pd
import numpy as np

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

if tf.test.gpu_device_name():
    print('GPU found')
else:
    print("No GPU found")

EPOCHS = 10
BATCH_SIZE = 16
# using two numpy arrays
features, labels = (np.array([np.random.sample((100,2))]), 
                    np.array([np.random.sample((100,1))]))
dataset = tf.data.Dataset.from_tensor_slices((features,labels)).repeat().batch(BATCH_SIZE)
iter = dataset.make_one_shot_iterator()
x, y = iter.get_next()
# make a simple model
net = tf.layers.dense(x, 8, activation=tf.tanh) # pass the first value from iter.get_next() as input
net = tf.layers.dense(net, 8, activation=tf.tanh)
prediction = tf.layers.dense(net, 1, activation=tf.tanh)
loss = tf.losses.mean_squared_error(prediction, y) # pass the second value from iter.get_net() as label
train_op = tf.train.AdamOptimizer().minimize(loss)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(EPOCHS):
        _, loss_value = sess.run([train_op, loss])
        print("Iter: {}, Loss: {:.4f}".format(i, loss_value))

No GPU found
Iter: 0, Loss: 0.1156
Iter: 1, Loss: 0.1114
Iter: 2, Loss: 0.1075
Iter: 3, Loss: 0.1039
Iter: 4, Loss: 0.1007
Iter: 5, Loss: 0.0977
Iter: 6, Loss: 0.0951
Iter: 7, Loss: 0.0928
Iter: 8, Loss: 0.0907
Iter: 9, Loss: 0.0890


In [54]:
EPOCHS = 20
BATCH_SIZE = 16
# create a placeholder to dynamically switch between batch sizes
batch_size = tf.placeholder(tf.int64)
x, y = tf.placeholder(tf.float32, shape=[None,2]), tf.placeholder(tf.float32, shape=[None,1])
dataset = tf.data.Dataset.from_tensor_slices((x, y)).batch(batch_size).repeat(EPOCHS).shuffle(1000)

# using two numpy arrays
train_data = (np.random.sample((100,2)), np.random.sample((100,1)))
test_data = (np.random.sample((20,2)), np.random.sample((20,1)))
iter = dataset.make_initializable_iterator()
features, labels = iter.get_next()

data_len = len(train_data[0])
batch_iter = int(data_len / BATCH_SIZE)

print(batch_iter)

# make a simple model
net = tf.layers.dense(features, 8, activation=tf.tanh) # pass the first value from iter.get_next() as input
net = tf.layers.dense(net, 8, activation=tf.tanh)
prediction = tf.layers.dense(net, 1, activation=tf.tanh)
loss = tf.losses.mean_squared_error(prediction, labels) # pass the second value from iter.get_net() as label
train_op = tf.train.AdamOptimizer().minimize(loss)
#######################################################
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # initialise iterator with train data
    sess.run(iter.initializer, feed_dict={ x: train_data[0], y: train_data[1], batch_size: BATCH_SIZE})
    print('Training...')
    for i in range(EPOCHS):
        tot_loss = 0
        for j in range(batch_iter):
            #print(tot_loss)
            _, loss_value = sess.run([train_op, loss])
            tot_loss += loss_value
        print("Iter: {}, Loss: {:.4f}".format(i, tot_loss / n_batches))
        pred = sess.run([ prediction] , feed_dict={x : np.random.sample((100,2)) , y :  np.random.sample((100,1))} )
        #print(pred)
    # initialise iterator with test data
    sess.run(iter.initializer, feed_dict={ x: test_data[0], y: test_data[1], batch_size: test_data[0].shape[0]})
    print('Test Loss: {:4f}'.format(sess.run(loss)))

6
Training...
Iter: 0, Loss: 0.0823
Iter: 1, Loss: 0.0757
Iter: 2, Loss: 0.0627
Iter: 3, Loss: 0.0693
Iter: 4, Loss: 0.0671
Iter: 5, Loss: 0.0573
Iter: 6, Loss: 0.0729
Iter: 7, Loss: 0.0718
Iter: 8, Loss: 0.0761
Iter: 9, Loss: 0.0627
Iter: 10, Loss: 0.0684
Iter: 11, Loss: 0.0698
Iter: 12, Loss: 0.0782
Iter: 13, Loss: 0.0536
Iter: 14, Loss: 0.0567
Iter: 15, Loss: 0.0518
Iter: 16, Loss: 0.0562
Iter: 17, Loss: 0.0533
Iter: 18, Loss: 0.0530
Iter: 19, Loss: 0.0608
Test Loss: 0.086351


In [55]:
import tensorflow as tf

n_epochs = 10
batch_size = 3

data_len = 30
batch_iter = int(data_len / batch_size)
buffer_size = data_len
## buffer size 에 따라 데이터 위치가 달라진다.
dataset = np.random.sample((data_len,2))
dataset = tf.data.Dataset.from_tensor_slices(dataset)
#dataset = tf.data.Dataset.range(data_len)
dataset = dataset.shuffle(buffer_size=buffer_size)
dataset = dataset.batch(batch_size)
dataset = dataset.repeat(n_epochs)
iterator = dataset.make_one_shot_iterator()
next_batch = iterator.get_next()

sess = tf.Session()
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(n_epochs) :
        print("epoch : " + str(i))
        for j in range( batch_iter ) : 
            print(sess.run(next_batch))
            print(sess.run(next_batch))

epoch : 0
[[0.38861064 0.80662275]
 [0.84220586 0.28659052]
 [0.76292752 0.96893581]]
[[0.9509802  0.32307409]
 [0.51649942 0.78463   ]
 [0.25130145 0.29988938]]
[[0.34296747 0.96906485]
 [0.25947147 0.18278038]
 [0.77702074 0.33729642]]
[[0.55526142 0.17521473]
 [0.12576605 0.01671396]
 [0.65668485 0.34100824]]
[[0.39777713 0.12445152]
 [0.67263397 0.34857138]
 [0.62364854 0.8399866 ]]
[[0.53383888 0.04481797]
 [0.06436878 0.87648199]
 [0.74354369 0.94909293]]
[[0.6136619  0.42288042]
 [0.81693805 0.06932447]
 [0.68545549 0.83400965]]
[[0.41347674 0.28570438]
 [0.78318312 0.8752748 ]
 [0.38969786 0.91789675]]
[[0.52811168 0.16744234]
 [0.7321212  0.46902616]
 [0.72751155 0.95246481]]
[[0.49476251 0.67437337]
 [0.62765519 0.33478614]
 [0.82145373 0.18141612]]
[[0.72751155 0.95246481]
 [0.52811168 0.16744234]
 [0.62765519 0.33478614]]
[[0.25130145 0.29988938]
 [0.84220586 0.28659052]
 [0.38861064 0.80662275]]
[[0.49476251 0.67437337]
 [0.06436878 0.87648199]
 [0.12576605 0.01671396]]
[[

OutOfRangeError: End of sequence
	 [[node IteratorGetNext_52 (defined at <ipython-input-55-145cd3a33c48>:17)  = IteratorGetNext[output_shapes=[[?,2]], output_types=[DT_DOUBLE], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_30)]]

Caused by op 'IteratorGetNext_52', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.5/dist-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-55-145cd3a33c48>", line 17, in <module>
    next_batch = iterator.get_next()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 421, in get_next
    name=name)), self._output_types,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
	 [[node IteratorGetNext_52 (defined at <ipython-input-55-145cd3a33c48>:17)  = IteratorGetNext[output_shapes=[[?,2]], output_types=[DT_DOUBLE], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_30)]]
